# User factory definition module and environment settings
general:
  factory_module: "my_factories.py"  # User-defined Python or pickle file containing the factory functions
  env_settings: "env_settings.yaml" # Environment settings (can also be a nested dictionary)
  norm_observations: false # Use VecNormalize to normalize the observations
  norm_rewards: true # Use VecNormalize to normalize the rewards

# Heuristic dataset generation
dataset:
  enabled: true
  quiet: false
  n_episodes: 200
  path: "data/heuristic_dataset.pkl"
  n_peaks: 5
  maxtem: 5
  mis_angle_min: -2.0e-4
  mis_angle_max: 2.0e-4
  policy: "default" # or a pickle path
  seed: 42

# Behavioral Cloning
bc:
  enabled: true
  quiet: false
  policy_save_path: "models/bc_policy.pt"
  torch_num_threads: 10
  n_envs: 4
  device: "mps"
  net_arch: [64, 64]
  learning_rate: 1e-4
  n_epochs: 10
  seed: 142

# PPO Fine-Tuning
ppo:
  enabled: true
  quiet: false
  continue_training: false
  skip_bc: false
  device: "cpu"
  n_envs: 10
  torch_num_threads: 1
  learning_rate: 3e-4
  total_timesteps: 400000
  ent_coef: 0.02
  exploration_settings:
    enabled: false
  tensorboard_log_dir: "logs/ppo"
  tensorboard_log_name: "PPO_MultiEnv"
  save_path: "models/ppo_policy"
  load_path: "models/ppo_policy"
  save_freq: 50000
  n_peaks: 5
  maxtem: 5
  mis_angle_min: -2.0e-4
  mis_angle_max: 2.0e-4
  seed: 242

# Evaluation
evaluation:
  enabled: true
  quiet: false
  n_episodes: 20
  agent_path: "models/bc_policy.pt"
  raw_rewards: false
  n_peaks: 5
  maxtem: 5
  mis_angle_min: -2.0e-4
  mis_angle_max: 2.0e-4
  seed: 342
  save_path: "evaluation/evaluation_results.yaml"
  message: "My evaluation"

