[project]
name = "calmly"
version = "0.1.0"
description = "Automated optical cavity alignment via reinforcement learning"
authors = [
  { name = "Artemiy Dmitriev", email = "artemiydmitriev@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-or-later"
license-files = ["LICEN[CS]E*"]
dependencies = [
  "numpy",
  "torch",
  "tqdm",
  "PyYAML",
  "gymnasium",
  "stable-baselines3",
  "imitation",
  "finesse"
]

[project.urls]
repository = "https://github.com/artemiy-dmitriev/calmly.git"

[project.scripts]
calmly-generate_dataset = "calmly.actions.generate_dataset:main"
calmly-train_bc = "calmly.actions.behavioral_cloning:main"
calmly-train_ppo = "calmly.actions.ppo_training:main"
calmly-evaluate = "calmly.actions.model_evaluation:main"
calmly-clean = "calmly.actions.clean:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
